#
# This file contains configuration flags to customize your blog
#

# The name of your blog
name: Barry Clark

# A short bio or description
description: Web Developer

# A URL pointing to your avatar or profile pic
# To use your Gravatar: (the one that GitHub uses for your profile pic)
#   1. Go to https://github.com/YOURUSERNAME/
#   2. Right click > Copy Image URL on your profile pic,
#   3. Take the first long ID from the URL and paste it in place of mine below
avatar: http://www.gravatar.com/avatar/36b4f56a7fa40d3c06e5afc4ed0b82b5?s=200

# Your disqus username, if you'd like blog commenting
disqus: barryclark

# Your Google Analytics web tracking code (e.g. UA-2110908-2)
google_analytics: UA-2530088-4

# Links used for your social icons
links:
  github: barryclark
  twitter: baznyc

markdown: rdiscount
pygments: true
permalink: /:title

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - scss
    - README.md